set_attack_value(AT_FAIR, AG_CATEGORY, 1);
set_attack_value(AT_FAIR, AG_SPRITE, sprite_get(string(plate_state) + "_fair"));
set_attack_value(AT_FAIR, AG_NUM_WINDOWS, 3);
set_attack_value(AT_FAIR, AG_HAS_LANDING_LAG, 1);
set_attack_value(AT_FAIR, AG_LANDING_LAG, 6);
set_attack_value(AT_FAIR, AG_HURTBOX_SPRITE, sprite_get("fair_hurt"));

set_window_value(AT_FAIR, 1, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FAIR, 1, AG_WINDOW_ANIM_FRAMES, 2);
set_window_value(AT_FAIR, 1, AG_WINDOW_ANIM_FRAME_START, 1);
set_window_value(AT_FAIR, 1, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));
set_window_value(AT_FAIR, 1, AG_WINDOW_SFX_FRAME, 8);

set_window_value(AT_FAIR, 2, AG_WINDOW_LENGTH, 21);
set_window_value(AT_FAIR, 2, AG_WINDOW_ANIM_FRAMES, 7);
set_window_value(AT_FAIR, 2, AG_WINDOW_ANIM_FRAME_START, 3);
set_window_value(AT_FAIR, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_FAIR, 2, AG_WINDOW_SFX, asset_get("sfx_spin"));

set_window_value(AT_FAIR, 3, AG_WINDOW_LENGTH, 10);
set_window_value(AT_FAIR, 3, AG_WINDOW_ANIM_FRAMES, 3);
set_window_value(AT_FAIR, 3, AG_WINDOW_ANIM_FRAME_START, 10);
set_window_value(AT_FAIR, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_FAIR, 8);

set_hitbox_value(AT_FAIR, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FAIR, 1, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 1, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 1, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 1, HG_WIDTH, 140);
set_hitbox_value(AT_FAIR, 1, HG_HEIGHT, 50);
set_hitbox_value(AT_FAIR, 1, HG_PRIORITY, 7);
set_hitbox_value(AT_FAIR, 1, HG_DAMAGE, 4);
set_hitbox_value(AT_FAIR, 1, HG_ANGLE, 40);
set_hitbox_value(AT_FAIR, 1, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 1, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 2, HG_HITBOX_GROUP, 1);
set_hitbox_value(AT_FAIR, 2, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 2, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 2, HG_HITBOX_X, 120);
set_hitbox_value(AT_FAIR, 2, HG_HITBOX_Y, -82 + 52);
set_hitbox_value(AT_FAIR, 2, HG_WIDTH, 20);
set_hitbox_value(AT_FAIR, 2, HG_HEIGHT, 20);
set_hitbox_value(AT_FAIR, 2, HG_PRIORITY, 5);
set_hitbox_value(AT_FAIR, 2, HG_DAMAGE, 10);
set_hitbox_value(AT_FAIR, 2, HG_ANGLE, 40);
set_hitbox_value(AT_FAIR, 2, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FAIR, 2, HG_KNOCKBACK_SCALING, .8);
set_hitbox_value(AT_FAIR, 2, HG_BASE_HITPAUSE, 10);
set_hitbox_value(AT_FAIR, 2, HG_HITPAUSE_SCALING, 0.5);
set_hitbox_value(AT_FAIR, 2, HG_HIT_SFX, asset_get("sfx_absa_kickhit"));
set_hitbox_value(AT_FAIR, 2, HG_VISUAL_EFFECT, 306);

set_hitbox_value(AT_FAIR, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 3, HG_HITBOX_GROUP, 2);
set_hitbox_value(AT_FAIR, 3, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 3, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(AT_FAIR, 3, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 3, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 3, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 3, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 3, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 3, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 3, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 3, HG_ANGLE, 30);
set_hitbox_value(AT_FAIR, 3, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FAIR, 3, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 3, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 4, HG_HITBOX_GROUP, 3);
set_hitbox_value(AT_FAIR, 4, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 4, HG_WINDOW_CREATION_FRAME, 6);
set_hitbox_value(AT_FAIR, 4, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 4, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 4, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 4, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 4, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 4, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 4, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 4, HG_ANGLE, 30);
set_hitbox_value(AT_FAIR, 4, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FAIR, 4, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 4, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 4, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 5, HG_HITBOX_GROUP, 4);
set_hitbox_value(AT_FAIR, 5, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 5, HG_WINDOW_CREATION_FRAME, 9);
set_hitbox_value(AT_FAIR, 5, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 5, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 5, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 5, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 5, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 5, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 5, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 5, HG_ANGLE, 30);
set_hitbox_value(AT_FAIR, 5, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FAIR, 5, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 5, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 5, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 6, HG_HITBOX_GROUP, 5);
set_hitbox_value(AT_FAIR, 6, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 6, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_FAIR, 6, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 6, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 6, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 6, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 6, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 6, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 6, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 6, HG_ANGLE, 30);
set_hitbox_value(AT_FAIR, 6, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FAIR, 6, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 6, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 6, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 7, HG_HITBOX_GROUP, 6);
set_hitbox_value(AT_FAIR, 7, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 7, HG_WINDOW_CREATION_FRAME, 15);
set_hitbox_value(AT_FAIR, 7, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 7, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 7, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 7, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 7, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 7, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 7, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 7, HG_ANGLE, 30);
set_hitbox_value(AT_FAIR, 7, HG_ANGLE_FLIPPER, 9);
set_hitbox_value(AT_FAIR, 7, HG_BASE_KNOCKBACK, 4);
set_hitbox_value(AT_FAIR, 7, HG_BASE_HITPAUSE, 3);
set_hitbox_value(AT_FAIR, 7, HG_HIT_SFX, asset_get("sfx_blow_medium2"));

set_hitbox_value(AT_FAIR, 8, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_FAIR, 8, HG_HITBOX_GROUP, 7);
set_hitbox_value(AT_FAIR, 8, HG_WINDOW, 2);
set_hitbox_value(AT_FAIR, 8, HG_WINDOW_CREATION_FRAME, 18);
set_hitbox_value(AT_FAIR, 8, HG_LIFETIME, 3);
set_hitbox_value(AT_FAIR, 8, HG_HITBOX_X, 40);
set_hitbox_value(AT_FAIR, 8, HG_HITBOX_Y, -80 + 52);
set_hitbox_value(AT_FAIR, 8, HG_WIDTH, 90);
set_hitbox_value(AT_FAIR, 8, HG_HEIGHT, 70);
set_hitbox_value(AT_FAIR, 8, HG_PRIORITY, 4);
set_hitbox_value(AT_FAIR, 8, HG_DAMAGE, 1);
set_hitbox_value(AT_FAIR, 8, HG_ANGLE, 45);
set_hitbox_value(AT_FAIR, 8, HG_BASE_KNOCKBACK, 6);
set_hitbox_value(AT_FAIR, 8, HG_KNOCKBACK_SCALING, .4);
set_hitbox_value(AT_FAIR, 8, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_FAIR, 8, HG_HITPAUSE_SCALING, .25);
set_hitbox_value(AT_FAIR, 8, HG_HIT_SFX, asset_get("sfx_blow_medium3"));

//24 frame, 6 animation frame